# Generated by Django 5.0.6 on 2024-08-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_age_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
