# Generated by Django 5.0.6 on 2024-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_bank_info_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='winner_bonus_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
