# Generated by Django 5.0.6 on 2024-08-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_winner_bonus_claimed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='winner_bonus_claimed',
        ),
    ]
