# Generated by Django 5.0.6 on 2024-08-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_winner_bonus_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='winner_bonus_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
